# Generated by Django 6.0.7 on 2026-08-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_active_users_verified(apps, schema_editor):
    """Keep accounts created before OTP verification able to sign in."""
    CustomUser = apps.get_model('account', 'CustomUser')
    CustomUser.objects.filter(is_active=True).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(mark_existing_active_users_verified, migrations.RunPython.noop),
    ]
