# Generated by Django 6.0.7 on 2026-07-28 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profile_covers/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('current_work', models.CharField(blank=True, help_text='Current job title or position', max_length=255)),
                ('professional_summary', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_links', models.TextField(blank=True, help_text='Add multiple links separated by commas')),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, help_text='List certifications separated by commas')),
                ('technical_skills', models.TextField(blank=True, help_text='List skills separated by commas')),
                ('soft_skills', models.TextField(blank=True, help_text='List skills separated by commas')),
                ('languages', models.TextField(blank=True, help_text='Languages and proficiency level')),
                ('desired_job_titles', models.CharField(blank=True, max_length=255)),
                ('notice_period', models.DateField(blank=True, help_text='When you can start a new job', null=True)),
                ('willing_to_relocate', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('open', 'Open to Opportunities')], default='open', max_length=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
