# Generated by Django 6.0.7 on 2026-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expected_salary',
            field=models.CharField(blank=True, help_text='e.g., $50,000 - $70,000', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('looking', 'Actively Looking'), ('open', 'Open to Opportunities')], default='open', max_length=20),
        ),
    ]
