# Generated by Django 6.0.7 on 2026-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_expected_salary_userprofile_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headquarters_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='official_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perks_benefits',
            field=models.TextField(blank=True, help_text='List perks and benefits separated by commas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x_url',
            field=models.URLField(blank=True, help_text='Company X (formerly Twitter) profile URL'),
        ),
    ]
