# Generated by Django 6.0.7 on 2026-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification pending'), ('verified', 'Verified'), ('rejected', 'Verification rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
