# Generated by Django 6.0.7 on 2026-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_discription', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=100)),
                ('job_discription', models.CharField(max_length=250)),
                ('job_experience', models.IntegerField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_stipend', models.IntegerField()),
                ('job_starting_date', models.CharField(max_length=20)),
                ('job_skills', models.TextField(max_length=100)),
            ],
        ),
    ]
