# Generated by Django 6.0.7 on 2026-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_jobs_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_discription',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_skills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_stipend',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
