# Generated by Django 6.0.7 on 2026-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='number_vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_skills',
            field=models.CharField(max_length=255),
        ),
    ]
